---

- name: install requirements
  hosts: all
  pre_tasks:
    - name: update repositories cache
      apt:
        update_cache: yes
    - package: name={{ item }} state=latest
      with_items:
        - thin-provisioning-tools
        - mylvmbackup
        - jq
        - libfile-copy-recursive-perl
        - xinetd
        - sudo
        - iproute
        - rsyslog
        - ca-certificates
        - sudo
        - python-apt
        - software-properties-common
    - name: install mysql prerequisite
      package: name="{{ item }}"
      with_items:
        - curl
        - lsb-release
    - name: install percona mysql repo
      shell: curl -O https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb && dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb
      args:
        creates: /etc/apt/sources.list.d/percona-release.list
        executable: /bin/bash
        chdir: /tmp
    - name: add custom mysql config file
      local_action:
        module: copy
        dest: custom.cnf
        content: |
          [mysqld]
  roles:
    - role: entercloudsuite.consul
      consul_version: 1.2.2
      consul_packer_provision: true
      consul_configs:
        main:
          bind_addr: 0.0.0.0
          client_addr: 0.0.0.0
          node_name: "{{ ansible_hostname }}"
          data_dir: "{{ consul_data_dir }}"
          encrypt: "K8n07GA/ZoANSmJ5zkvgOg=="
          enable_syslog: true
          datacenter: automium
          server: true
          ui: true
    - role: entercloudsuite.consul-template
      consul_template_version: 0.19.5
      consul_template_use_systemd: true
      consul_template_staging_area: /var/spool
    - role: entercloudsuite.haproxy
      haproxy_user: admin
      haproxy_pass: admin
    - role: entercloudsuite.backup
      restic_version: 0.9.2
      os_api: dummy_api
      os_region: dummy_region
      os_project_id: dummy_project_id
      os_project: dummy_project
      os_user: dummy_user
      os_password: dummy_password
    - role: entercloudsuite.pmm_client
      pmm_client_version: 1.14.1
      pmm_client_enabled: False
    - role: ansible-mysql
      mysql_root_username: root
      mysql_root_password: root
      mysql_root_password_update: yes
      mysql_packages:
        - percona-server-server-5.7
        - percona-xtrabackup-24
      mysql_config_include_files:
        - src: custom.cnf
  post_tasks:
    - name: download restic https://github.com/restic/restic/pull/1719#pullrequestreview-119247068
      get_url:
        url: https://swift.it-mil1.entercloudsuite.com/v1/KEY_d51f5387474f40c6bd2975ccf34c7ea0/resticbin/restic
        dest: "/usr/local/bin/restic"
        mode: 0540

- name: prepare virtualenv
  hosts: all
  tasks:
    - name: create var project path
      set_fact:
        script_path: /usr/src/cloud
    - name: install requirements
      package: name="{{ item }}"
      with_items:
        - libffi-dev
        - libssl-dev
        - python-minimal
        - python-pip
        - virtualenv
    - name: create directory
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ script_path }}"
        - "{{ script_path }}/roles"
    - name: create requirements.txt
      copy:
        content: |
          ansible==2.6.2
          asn1crypto==0.23.0
          bcrypt==3.1.4
          cffi==1.11.2
          cryptography==2.1.3
          enum34==1.1.6
          idna==2.6
          ipaddress==1.0.18
          Jinja2==2.10
          MarkupSafe==1.0
          paramiko==2.4.0
          pyasn1==0.3.7
          pycparser==2.18
          pycrypto==2.6.1
          PyNaCl==1.2.0
          PyYAML==3.12
          six==1.11.0
          jmespath==0.9.3
        dest: "{{ script_path }}/requirements.txt"
        remote_src: yes
    - name: create requirements.yml
      copy:
        content: |
          - src: entercloudsuite.mysql
            version: 1.0.1
          - src: entercloudsuite.haproxy
            version: 1.1.3
          - src: entercloudsuite.consul-template
            version: 1.0.1
          - src: entercloudsuite.consul
            version: 1.0.1
          - src: entercloudsuite.pmm_client
            version: 1.0.1
          - src: entercloudsuite.backup
            version: 1.1.4
        dest: "{{ script_path }}/requirements.yml"
        remote_src: yes
    - name: install python requirements
      pip:
        requirements: "{{ script_path }}/requirements.txt"
        virtualenv: "{{ script_path }}/venv"
    - name: install ansible roles
      shell: source {{ script_path }}/venv/bin/activate && ansible-galaxy install -f -p roles -r requirements.yml
      args:
        chdir: "{{ script_path }}"
        executable: /bin/bash
